### ISSUE TITLE
Request to delete data from Production 

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#1102]
## Overview

I had to upload test data to Production during a workshop this morning due to changes on Staging which I wasn't aware of. I now can't delete this data from Django because of a loop I get caught in between "Facility lists" and "Sources".

### Expected Behavior

I need to delete the test data from Production. 

### Actual Behavior

I get error messages when I try to delete the test data from both the Facility List menu and the Sources menu.

### Demo

![Screenshot 2020-09-09 at 17 16 27](https://user-images.githubusercontent.com/46344729/92625148-37adc880-f2c0-11ea-8d3e-f682f658c5dc.png)

![Screenshot 2020-09-09 at 17 16 53](https://user-images.githubusercontent.com/46344729/92625205-472d1180-f2c0-11ea-9fd3-87c414a1e74e.png)

![Screenshot 2020-09-09 at 17 18 25](https://user-images.githubusercontent.com/46344729/92625395-7d6a9100-f2c0-11ea-98a2-03e76f611ccc.png)

### Additional context

The list to delete is called "IndustriALL Workshop test list" from the Contributor "Katie OAR".

**Comment by jwalgran** [comment]
I deleted this using the following (cumbersome) process.

- Attempt to delete the source. The page returned has a link to all the list items that must first be deleted.
- For each link on the page, 
  - modify the url to end in `/delete` rather than `change` and visit the delete page. The delete page will list all of the `FacilityMatch` records that need to be deleted before the `FacilityListItem` can be deleted
  - Browse each of the `FacilityMatch` links in new tabs and delete them.
  - Refresh the `FacilityListItem` delete page and delete it
- When all of `FacilityListItem`s have been deleted, the `Source` can be deleted
- After deleting the `Source`, delete the `FacilityList`
