### ISSUE TITLE
Add "back to top" button at the bottom of each page of a supplier list

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#117]
## Overview

Add a "back to top" button at the bottom of each page of a supplier list, when the list is being viewed through the "My lists" section of a user account. 

### Is your feature request related to a problem? Please describe.

Navigating within the "My lists" section of a user account is currently pretty laborious, and involves a lot of scrolling and clicking. 

When a user has worked through the Confirm / Deny process on 100 facilities, they may like to jump quickly back to the top of their list to check through the entries, but currently have to scroll back to the top. 

### Describe the solution you'd like

A "back to top" button at the bottom of each page of a supplier list which users can click to jump back to the top of the page. 

### Additional Context

N/A

**Comment by kellyi** [comment]
I believe we have circumvented the need for this by paginating the facility list details page so that users no longer need to scroll through all items:

![Screen Shot 2019-06-21 at 10 58 54 AM](https://user-images.githubusercontent.com/4165523/59931763-b85e7b80-9413-11e9-84bc-0d5e23e0e106.png)

I'm going to close this but feel free to re-open it if it is still desirable to add this feature!
