### ISSUE TITLE
When registering for a Contributor account on the OAR, users are currently able to give their personal name as the Account name

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#120]
## Overview

When Registering for a Contributor account on the OAR, users are able to use their personal name, rather than their organisation name, for the Account Name on the site. 

### Expected Behavior

Users should only be able to use an organisation name for their account on the OAR.

### Actual Behavior

Users are able to give their personal name, e.g. Katie Shaw, for the account name on the OAR. 

### Steps to Reproduce

* Click "Register" on the OAR site
* There are no restrictions in the Account Name field on the site, and (from memory) no detailed explanation that the Account Name will appear on the front end of the site and that an organisation name, rather than an individual's name, should be used.

### Demo

N/A

### Additional context

This is a problem because the OAR site could end up looking like it's populated by a collection of individuals, whose names mean nothing to most users, rather than a series of different organisations.

**Comment by kellyi** [comment]
I believe we have address this by indicating that the "Name" field is the "Contributor Name" on the registration form:

![Screen Shot 2019-06-21 at 11 17 10 AM](https://user-images.githubusercontent.com/4165523/59932880-34f25980-9416-11e9-8652-6458045f102c.png)

We also now suppress contributors without any active facility lists from the facilities search menu, so a user who mistakenly gave a personal name rather than a contributor name in that field but did not upload a list would not appear in the search menu.

**Comment by katieashaw** [comment]
Thanks @kellyi ! @nataliegrillon and I still feel like this is a slightly confusing field and we've seen brand users continue to get this wrong in the first instance, even since the switch to "Contributor name" was made. 

Could we add this explanatory text _before_ the "Your contributor name will appear..." sentence:

"If you are uploading a supplier list on behalf of the organisation you work for, you should add the organisation name here, not your personal name."

**Comment by kellyi** [comment]
Hi @katieashaw! Thanks for clarifying. We can add that text before the sentence. I have an open pull request with some bugfixes so I'll add the change there.

**Comment by kellyi** [comment]
Shares points with #569

**Comment by katieashaw** [comment]
Thank you!!
