### ISSUE TITLE
Using AND logic in the search filters is the opposite of standard proceedure

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#131]
## Overview

A site user has fed back that using AND logic in the search filters is the opposite of standard procedure. 

### Expected Behavior

The user feels the site should use OR logic in the search filters and that this should either be changed, or stated explicitly in the UI that we're using AND logic.

### Actual Behavior

The site uses AND logic in the search filters. 

### Steps to Reproduce

* Search the site, selecting multiple filters from the Contributor and Country fields in combination. 

### Demo

N/A

### Additional context

The email from the site user is here: Removed link to avoid sharing personal contact details. Text of email in comment below.

The FAQ page the email refers to is here, and the question is in the "Searching the OAR" section: https://info.openapparel.org/faq/

**Comment by dboyer** [comment]
Pasting content of email here to avoid displaying personal contact details:

My colleagues and I are very excited at the prospect of working with the data you’ve collected here, but I felt I should contact you about a small issue we all experienced.

It seems you’re aware of this issue as it’s listed in your FAQ, but I felt the need to reach out and emphasize to you the counter­intuitive nature of using AND logic instead of
OR.  I understand your reasoning for setting it up this way after reading your FAQ entry on the topic, but I still think you should reconsider the current design of the search box. 
My colleagues and I are very interested in the data you’ve accumulated, but it confused us all when we first interacted with it that these fields are using AND logic.  The issue is
not that you’ve chosen to use AND logic, but that you don’t indicate it anywhere in your UI when it is the opposite of standard procedure for a checkbox list in a query builder.  I
feel like titling each of the drop­downs “Filter by X” actually suggests that they all function the same.
 
I suggest adding a little note in the title for that dropdown, or just replacing it with OR logic and adding a new box that says something like “Search for Shared Facilities” or
something similar.  The UI should definitely reflect the fact that this is a known issue, as it’s the only FAQ entry for Search.
