### ISSUE TITLE
When downloading data from the site, is it possible for it to be separated out into more columns?

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#133]
## Overview

When downloading data from the site, is it possible to separate out the address information into more columns?

All address information  is currently downloaded into one column. 

### Is your feature request related to a problem? Please describe.

This request has been made by a user as she, and many other organisations, organise their data in this way, rather than having all of the address information in one column. 

### Describe the solution you'd like

Address information downloaded from the site should populate into individual columns as follows:

*Street name and number
*City
*Province
*Zip code
*Country 

### Additional Context

N/A

**Comment by jwalgran** [comment]
We will never be able to do this for all facilities, since many of the submitted submitted addresses are relatively unstructured. The Google geocoder does attempt to break up the address into individual components when it can. 

We go have those results stored under the `processing_results` field on the `api_facilitylistitem` table, but I am concerned about the performance of parsing them out at the time of CSV generation. We may want to consider adding nullable address component fields to the `api_facilitylistitem` table that are updated by the batch processing, and could be backfilled with a management command.

**Comment by katieashaw** [comment]
CC'ing @nataliegrillon on this. Perhaps this is something we could consider offering as a paid-for service, for the users who are specifically interested in this?

**Comment by katieashaw** [comment]
Closed as no longer considered necessary - users can run formulas to split out data per their requirements upon download.
