### ISSUE TITLE
All links to info website should open in new tab

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1510]
## Overview

For any links to info.openapparel.org on the map site, we'd like them to open in a new tab when clicked. This includes almost all the new Header/Footer links. 

cc @katieashaw 

Shares point with #1512

**Comment by katieashaw** [comment]
Can I ask @lederer your views on this. Hannah & I are both slightly on the fence about whether links between info.openapparel.org and openapparel.org should open in new tabs. We think "yes they should open in new tabs" given that technically these are two different sites. But the "no" counter argument is that we're trying to create a more seamless experience between the two sites & the new header menu bar etc does a lot of that work for us. Do you have a view on this?

**Comment by lederer** [comment]
Good question. I think it might depend on the direction… 

If you're starting on the info site, I would posit that "Explore…" should open in the same tab (as it currently does). The rationale being that you're first getting the scoop on what this thing is, figuring out if it's for you, and ok now you've learned enough, let's do it. Done with the info site, don't keep it around, let's get to work in the app.

Whereas once you're in the app, you're doing work. Searching, maybe editing, etc. It might've take a fair amount of work to navigate to _these_ coordinates at _this_ zoom level, looking at results matching _these_ filters. You don't want to lose that work. But you may need some additional context about the OAR in parallel with that. So in that light, clicking from the app to the info site should open in a new tab.

I would advocate for that approach. But I'll include a couple of counterpoints:
- It creates an inconsistency between the app and info site. I think that's reasonable, but nonetheless it has its costs.
- There's a good general argument to be made that most links should not open in a new tab – because if someone wants a link to open in a new tab, they can choose to do that on their own (via right-click menu, etc). It's a good rule of thumb, since _open in new tab_ is overused in the wild. But I think exceptions are reasonable when there's a decent, use case-driven rationale like above.

**Comment by katieashaw** [comment]
This is so helpful, thanks @lederer !
