### ISSUE TITLE
Formatting - long Facility Name - can't see address

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1573]
## Overview

https://openapparel.org/facilities/VN20190859R5D0G

When looking at this facility, I cannot see the primary address, seemingly because the facility name is too long. 

![Screen Shot 2022-01-10 at 11 52 44 AM](https://user-images.githubusercontent.com/80268596/148754263-a3fc31a7-b516-4ea2-b5b0-c10631c4f04b.png)

cc @katieashaw

**Comment by hlennett** [comment]
Another example: https://openapparel.org/facilities/BD2020066BSJ52K?q=dird&contributors=2519

**Comment by jwalgran** [comment]
Our new sidebar design that is launching with extended profile moves name and address out of the header into dedicated fields that can expand to take up as much space as needed.

We will likely not plan to redesign/rework the existing sidebar since we are so close to releasing the new sidebar. Please let us know if that plan works for you.

<img width="183" alt="Screen Shot 2022-02-18 at 8 28 34 AM" src="https://user-images.githubusercontent.com/17363/154712438-62f15ca8-0526-4df8-8c4e-0c7a08c8415d.png">

**Comment by hlennett** [comment]
No urgency to resolve sooner, if it's getting fixed as part of the new sidebar. Thank you, Justin!

**Comment by hlennett** [comment]
@mariel-oar This was resolved with EP. Feel free to close.
