### ISSUE TITLE
Upload issues with Extended Fields

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#1638]
# Draft

1. People had to follow different work flows to upload the same file

- Mariel: format data in excel -> save as csv to a local folder -> upload to OAR -> "An error prevented uploading that file." 
- Natalie: format data in google sheets -> download as csv -> upload to OAR -> success 

- Moving excel CSV to Google sheets caused changes to formatting (headers became capitalized). Had to revert back to lowercase for it to be accepted. 

Opened the excel-formatted CSVs in Text Edit and saw the following
- In the [SanMar data](https://drive.google.com/file/d/1JSof38xjvwGqZY3s8Z4twTO702jJGXD0/view?usp=sharing), there were quotation marks around some of the values but not others. 
- In the [Scotch & Soda data](https://drive.google.com/file/d/1-O2Ph3N8EQayBWnghUNKgXcGMORKotys/view?usp=sharing), there were commas, usually four, at the end of some of the rows. Both data sets, as formatted in excel are attached. 
Despite those formatting, both of these data sets when uploaded to GS, then re-downloaded as CSV then uploaded, worked.

- Upload handling is much more sensitive than we expected it to be. This could be a huge challenge to users, who may use Excel or other applications to format their data. 
 
Issues with the processing_type and facility_type fields: 

- processing_type is not accepting any types that are not explicitly listed in the taxonomy. Our understanding is that processing_type should accept any data and do a fuzzy match against the taxonomy. Any matches with taxonomy would be displayed, any other values would only be available on download. 

- When the processing_type column is removed altogether an error for facility_type values of "Main Production Site or Subcontractor/Processor" resulted in an error. 

We understand that this is because, for facility_type, the intention is that system requires that it have an exact match in the taxonomy. 

Related: OAR has requested information on whether they need to change to processing_type & facility_type fields (see discussion in Slack).

**Comment by TaiWilkin** [comment]
Potentially related Rollbar errors for reference:
https://rollbar.com/OpenApparelRegistry/OpenApparelRegistry/items/203/
https://rollbar.com/OpenApparelRegistry/OpenApparelRegistry/items/594/

**Comment by obrienad** [comment]
Additional data uploads here: https://drive.google.com/drive/folders/162AQ5ryaGIeHKoIWAILq9jwt8ytjvreQ?usp=sharing

**Comment by mariel-oar** [comment]
Hi @jwalgran, 
As we discussed today, Hannah encountered an error when uploading another extended fields file. 

It triggered the error seen in the attached screenshot. 
![image](https://user-images.githubusercontent.com/97469356/154766916-23425cb6-57ef-4bcc-9b69-503ce67543aa.png)

The list she was working with is called: Outerknown 2021 Facility List. I downloaded it from the processing page (not the raw file), and that download is attached: [1468_Outerknown 2021 Facility List_2_18_2022.csv](https://github.com/open-apparel-registry/open-apparel-registry/files/8100685/1468_Outerknown.2021.Facility.List_2_18_2022.csv)

I will also flag this for @hlennett so that she can provide the original file.

**Comment by hlennett** [comment]
This was a user upload and was not a part of extended fields. Just a regular user uploading on prod, so we do not have the raw file. Here is a link to the list: https://openapparel.org/lists/1468?status=ERROR_PARSING&page=1&rowsPerPage=20

**Comment by mariel-oar** [comment]
Here is another example of an excel file that would not upload to production (this was a regular upload, not for EP). Hannah took this file and saved as csv, then it successfully uploaded to staging.

[Embedded Map CSV Template - boohoo.xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/8109729/Embedded.Map.CSV.Template.-.boohoo.xlsx)

@obrienad, @jwalgran, let me know if you'd like a separate ticket for non-EP upload issues. Adding here since it all seems to be a long the excel/csv thread.

**Comment by mariel-oar** [comment]
Another error that came up when the Boohoo list (from previous comment) was uploaded to prod: 

![image](https://user-images.githubusercontent.com/97469356/155173897-f3fd7282-53e2-4294-8a0b-4a1374a3cb26.png)

Adding to this ticket since it seems related to the other upload issues. lmk if you want me to create separate tickets. Thanks!

**Comment by hlennett** [comment]
^ You can find that error here: https://openapparel.org/lists/1474?status=ERROR_PARSING&page=1&rowsPerPage=20
