### ISSUE TITLE
Add a data migration to create extended profile fields for existing facility claims

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1648]
## Overview

In #1639 we integrated the facility claim with extended fields. Add a data migration to create extended profile fields for existing facility claims.

### Describe the solution you'd like

- [x] Work with the OAR team to map legacy facility_type and processing_type values to the new taxonomy
  - The exiting taxonomy should already incorporate all of the values from the claim if run them through `get_facility_and_processing_type` 
- [ ] Add a data migration
  - Create extended fields from existing claim data
  - For facility_type and production_type, set `raw_values` to the existing, legacy field values and `matched_values` to the appropriate taxonomy values.
- [X] Download a list of emails associated with claimed facilities to notify them of migration. (see https://github.com/open-apparel-registry/open-apparel-registry/issues/1648#issuecomment-1045009327)

**Comment by obrienad** [comment]
@mariel-oar 

Tai created a [mapping of values ](https://docs.google.com/document/d/1qfexjxlRmdzR9_NLzG45Knc_l2-Dxhn6JEnqYyKV4eY/edit?usp=sharing)currently in production (for facility types and processing types combined), as they appear after running through the processing script, in the format “Old Value: ‘New facility_type’, ‘New processing_type’“.

Could you confirm that the successful matches are correct and provide us with the desired categorizations for the unmatched values?

The sooner you can provide us this feedback the better, since this is blocking migrating that data, which we know is your priority!
