### ISSUE TITLE
Staging uploads stuck in processing

### ISSUE THREAD

**Issue by vrwOAR** [open-apparel-registry/open-apparel-registry#1724]
## Overview

Uploaded 7 files for testing of the March 17 staging release and only [1](https://staging.openapparel.org/lists/786) has gone through processing. The other 6 remain stuck at various stages of processing. @ [Geocoded stage-](https://staging.openapparel.org/lists/787) A uploaded stage [Riachuelo resale Excel](https://staging.openapparel.org/lists/788) [Riachuelo resale CSV](https://staging.openapparel.org/lists/789) [Osklen tier 3 excel](https://staging.openapparel.org/lists/790) [Osklen tier 2 excel](https://staging.openapparel.org/lists/791) [Osklen tier 1 excel](https://staging.openapparel.org/lists/792) . 

### Expected Behavior

The files should proceed through processing. 

### Actual Behavior

Though they have been moving slowly, this feels longer than the expected time for processing. First file uploaded @ 7:33PM EST, most recent at 8:06PM EST; over an hour for processing at this point.

### Steps to Reproduce

* contribute upload to staging.openapparel.org
* describe the environment: MacBook Pro, Monterey 12.0.1, Opera GX

**Comment by TaiWilkin** [comment]
Initial research: 
These lists have all now completed processing. It looks like the delays were related to the time between creating the batch jobs and the batch jobs starting; and the time taken for geocoding (geocoding time estimated as the time between parsing completing and matching starting). 
https://docs.google.com/spreadsheets/d/1kehu5yFdLAbQPmSUi0W7GoRISAjL6-v7kYHxSOlrH3Y/edit#gid=0
<img width="942" alt="Screen Shot 2022-03-18 at 7 43 35 AM" src="https://user-images.githubusercontent.com/21046714/158997503-be6cc20e-4f5c-4c41-be5c-878889b3b236.png">

**Comment by jwalgran** [comment]
From @mariel-oar on June 2 2022

>it looks like lists are getting stuck on staging again:
List from Tyler: https://staging.openapparel.org/dashboard/lists/?contributor=2733
List from Hannah: https://staging.openapparel.org/dashboard/lists/?contributor=1183
>Do you know if this is the resource pricing issue?

Browsing the Spot Request section of the AWS Console (ec2sp/v2/home?region=eu-west-1#/spot) I could see that there were no active spot requests and the list of history events was reporting that instance were not available at our specified price

I attempted to redeploy stating with an increased `batch_default_ce_spot_fleet_bid_percentage` value but provisioning failed with the message

>Error: error deleting Batch Compute Environment : Cannot delete, found existing JobQueue relationship

I cancels all the queued jobs and tried again but that did not work.

I manually resubmitted all the jobs I had canceled through the Batch Console and they succeeded

There is a discussion of the error here https://discuss.hashicorp.com/t/error-error-deleting-batch-compute-environment-cannot-delete-found-existing-jobqueue-relationship/5408/4 that includes this post

>I just ran into the same issue and discovered this thread.
I found that using both the create_before_destroy lifecycle setting and configuring a compute_environment_name_prefix instead of a constant compute_environment_name appears to have solved the problem.
