### ISSUE TITLE
Pressing the enter key in a form field should submit the form

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#183]
## Overview

The default behavior for a web form is to submit the form if you press <kbd>Enter</kbd>. We should provide this behavior.

### Describe the solution you'd like

- Pressing <kbd>Enter</kbd> with the focus on any field should submit the form. 
  - Login
  - Registration
  - Search
    - This one may not be possible if our select library does not support the proper event handling. If I focus the country field and type <kbd>c</kbd> <kbd>h</kbd> <kbd>i</kbd> <kbd>n</kbd>  <kbd>Enter</kbd>, "China" should be selected, as it is now. If I immediately press  <kbd>Enter</kbd> again we would prefer that the form is submitted.

**Comment by kellyi** [comment]
I opted not to do this:

> This one may not be possible if our select library does not support the proper event handling. If I focus the country field and type c h i n Enter, "China" should be selected, as it is now. If I immediately press Enter again we would prefer that the form is submitted.

here.

I did update the facility name search to submit on pressing enter because it is a traditional text input:

![Screen Shot 2019-03-14 at 11 38 07 AM](https://user-images.githubusercontent.com/4165523/54370256-b2574280-464d-11e9-84e3-fbcda1ddd274.png)

However, the other filters on that tab are select boxes with text search and the built-in react-select behavior is to have it choose an option from the list on pressing enter.
