### ISSUE TITLE
Add a new filter on the home page to search by sector 

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#1833]
## Overview

Add a new filter on the home page to search by sector 

Depends on #1838 

### Describe the solution you'd like

- Add a multi-select field labeled "Sector"
-  Ad the field "above the fold" between the Contributor Name field and the Search button
-   Populate the dropdown with the sector list returned from the `/api/sectors` **but** dekay loading the sector list choices until the field is focused
- Like other multi-select fields, selected values should update a repeating `sectors` query string parameter in the URL
- Pass the selected sector options to the facility search API

**Comment by jwalgran** [comment]
@mariel-oar I added the `client action needed` label because we need to decide the following

 Should the new Sector filter drop down be visible by default on the sidebar or hidden unlit "More Filters" is clicked?

**Comment by mariel-oar** [comment]
@jwalgran, Good question, is it possible to display it but not populate it until it's clicked on (would that help anything?) 

It's kind of the key differentiator for OAR vs OSH, so feels like it needs to be above the fold, but I'm worried about that since the taxonomy for it is open ended (a la product type). 

We could display it during beta at least to test things, and hide it later on if we see it hurts performance too much?

**Comment by jwalgran** [comment]
Thanks for the guidance, @mariel-oar  We will:

-  Add the sector field to the sidebar "above the fold" between the Contributor Name field and the Search button
- Delay loading the sector list choices until the field is focused
