### ISSUE TITLE
Redirect Openapparel.org (prod) to the new URL

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#1895]
NOTE Depending on the decision made about implementing #2088 there may be little additional work required to complete this issue.

## Technical implementation

 - Attach the prod OAR CloudFront function to the prod distribution

**Comment by mariel-oar** [comment]
@obrienad @jwalgran , is the question here what will the new URL be? 

The new URL is opensupplyhub.org

**Comment by jwalgran** [comment]
We have decided that:

- We are going to implement the conditional redirect so that existing embedded maps will still load use `openapparel.org` for a period of time (#2088)
- The new production URL will be opensupplyhub.org

That resolves the open questions for me so I will remove the client action needed tag.

**Comment by jwalgran** [comment]
Reduced to 1 because the conditional redirect is set up and just needs to be enabled.

**Comment by obrienad** [comment]
FYI @mariel-oar (see Justin's note above)
