### ISSUE TITLE
Add content to the facility details page excluding the interactive map

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2075]
Depends on #2075

Refer the the "Facility Profile" section of the Figma board

Icons can be exported from Figma by selecting them then using the Export panel at the right side of the page.

Show all content on the new details page except for the interactive map

- Do NOT implement "last updated" as part of this issue
- Add the new "Report" dropdown button to contain the existing links that appear at the bottom of the facility profile
- The section at the bottom of the new page for showing associated contributors is collapsed by default 
- Add a "drawer' component that opens on the right and shows multiple values for a field instead of an expanding list.
   -  This drawer is used throughout the new site design so the functionality should be reusable
   -  At mobile widths the drawer should cover the entire page

<img width="382" alt="Screen Shot 2022-08-19 at 2 10 53 PM" src="https://user-images.githubusercontent.com/17363/185708649-88c55b03-6c5f-4e8a-9b10-207006e5ae46.png">

<img width="654" alt="Screen Shot 2022-08-19 at 2 29 48 PM" src="https://user-images.githubusercontent.com/17363/185709815-4fc7466d-b44f-45a1-93f4-5ea4d5320b19.png">

**Comment by mariel-oar** [comment]
Comments from the OAR team: 

- can we make the font for the OAR ID itself size 18 instead of 14 
- is it possible to pin the "Description" data point as the last data point and allow it to be the width of the 2 columns, instead of wrapping into the one column. E.g. see [this facility's](https://9f692df0338dcbc9848646c6.openapparel.org/facilities/PK2019087CM6HW9) description
- Note that description only shows up for claimed facilities if the owner has entered a description
