### ISSUE TITLE
Add an interactive map to the facility details page

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2076]
Depends on #2075

Refer the the "Facility Profile" section of the Figma board

Icons can be exported from Figma by selecting them then using the Export panel at the right side of the page.

Disable scroll zoom on the map so that content below the map is easily accessible.

<img width="495" alt="Screen Shot 2022-08-19 at 2 31 23 PM" src="https://user-images.githubusercontent.com/17363/185710254-05ba71b5-7acf-4f93-8401-f3b12f6a2fc8.png">

**Comment by obrienad** [comment]
Client action needed: OAR requested to sign-off on #2075 first before commencing this issue.

**Comment by TaiWilkin** [comment]
Feedback on #2075 to be applied in this ticket:
Comments from the OAR team:
- can we make the font for the OAR ID itself size 18 instead of 14
- is it possible to pin the "Description" data point as the last data point and allow it to be the width of the 2 columns, instead of wrapping into the one column. E.g. see this facility's description (note that description only shows up for claimed facilities if the owner has entered a description)
