### ISSUE TITLE
Navigating from the facility detail page to the search results page should maintain state

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2133]
Navigating back to the search results should not run the search and should maintain scroll position.

Here is a screencast of the current interaction in which the search is rerun and state is lost.

![2022-09-12 08 07 38](https://user-images.githubusercontent.com/17363/189689895-7efeb29a-a1cd-4c7b-806e-7d5aa1846f42.gif)

**Comment by TaiWilkin** [comment]
Feedback on #2075 to be applied in this ticket:
Comments from the OAR team:
- can we make the font for the OAR ID itself size 18 instead of 14
- is it possible to pin the "Description" data point as the last data point and allow it to be the width of the 2 columns, instead of wrapping into the one column. E.g. see this facility's description (note that description only shows up for claimed facilities if the owner has entered a description)
