### ISSUE TITLE
In Chrome, text in modal dialogs is not translated until the dialog is clicked

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#228]
## Overview

When a modal dialog is shown in Chrome, the text is displayed in English even if a different language is selected. When browsing with Firefox, the text is initially shown in English but is translated after a short delay.

### Expected Behavior

When a modal dialog is opened in Chrome, the language of the text in that dialog matches the language selected on the header bar.

### Actual Behavior

When a modal dialog is opened in chrome, the text in that dialog is displayed in English. Clicking on whitespace in the dialog triggers the translation.

### Steps to Reproduce

* Browse the login page in a non-English language (http://localhost:6543/auth/login#googtrans(en|da))
* Click the password reset link

### Demo

![2019-02-25 11 15 57](https://user-images.githubusercontent.com/17363/53359445-3096b380-38f0-11e9-872e-71afe2e3f39f.gif)

### Additional context

We are using a client-side Google translation library

https://github.com/open-apparel-registry/open-apparel-registry/blob/7352adcb210557e7db99cfd0683e53b957305090/src/app/public/index.html#L71-L76

**Comment by kellyi** [comment]
I just tested this out in Chrome and Firefox and the dialogs are now translated immediately after they appear rather than after interaction. There's still a small flicker when they are rendered in English before having the text adjusted into the target translation language, but I think this is an unavoidable consequence of how React rendering interacts with Google Translate.

I believe this got fixed by https://github.com/open-apparel-registry/open-apparel-registry/pull/322
