### ISSUE TITLE
Fix embedded map freeze

### ISSUE THREAD

**Issue by TaiWilkin** [open-apparel-registry/open-apparel-registry#2313]
## Overview

In embedded maps, if embedExtendedFields is undefined, the line `<ShowOnly when={!embed || embedExtendedFields.length}>` throws an error. This error is caught by the sidebar error catcher, which attempts to reload the section, which the reloads infinitely, causing the page to freeze. 

### Expected Behavior

Show the extended fields explanatory text only when the site is not in embed or their are embed extended fields. The page should not break. 

### Actual Behavior

The page freezes.

### Steps to Reproduce

* Visit https://opensupplyhub.org/facilities?contributors=3756&embed=1

### Demo

https://rollbar.com/OpenApparelRegistry/OpenSupplyHub/items/141/?item_page=0&#traceback

### Additional Context

#2314 is a separate issue for the fact that the sidebar goes into an infinite loop when there's an error.

**Comment by TaiWilkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Civic-Apps-5c8fabc1177a1c1f6672f901/issues/open-apparel-registry/open-apparel-registry/2313?planning-poker) with Zenhub @jwalgran @nanotubing

**Comment by vrwOAR** [comment]
Testing Findings:

We did additional testing because the second map that was mentioned with the bug, Sunrock, is up without the looping & reloading. It appears that if the user has not configured the map on their end, the URL will result in the loop. Once configured, the looping is resolved. We attempted to recreate this with [adidas](https://opensupplyhub.org/facilities?contributors=3617) and [Arcteryx](https://opensupplyhub.org/facilities?contributors=1534), both accounts did not have EM configured for their accounts. The looping behavior was reproduced.  [adidas](https://opensupplyhub.org/facilities/?contributors=3617&embed=1)

Once we configured the page with [Arcteryx](https://opensupplyhub.org/facilities/?contributors=1534&embed=1), the looping stopped. Which is a similar behavior to [Sunrock's](https://opensupplyhub.org/facilities/?contributors=3734&embed=1) EM page.
