### ISSUE TITLE
Implement the previous download format

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2392]
Depends on the recommendation in #2388. If this is undoing the change is the best approach: restore the old download (1 row per facility, all contributor values concatenated into single cell)

Downloads should remain to restricted to a maximum of 10k results.

@mariel-oar This issue was split from #2388 for estimation purposes

**Comment by jwalgran** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Civic-Apps-5c8fabc1177a1c1f6672f901/issues/open-apparel-registry/open-apparel-registry/2392?planning-poker) with Zenhub @TaiWilkin

**Comment by mariel-oar** [comment]
@jwalgran , to make sure we are on the same page: we do not want the 10k facility download limit lifted - just reverting to the previous format. They are kind of related because we had instituted the 10k limit in response to download times being much slower with the new format, so wanted to be clear.

**Comment by jwalgran** [comment]
Thanks for clarifying that. I updated the issue description to not that the 10k restriction should remain in effect.

**Comment by jwalgran** [comment]
@mariel-oar I'm adding the client action needed label to this while the OS Hub team reviews the document linked in #2388 and decides whether or not to move forward with this.

**Comment by obrienad** [comment]
Removed CAN as OS Hub approved this.
