### ISSUE TITLE
The "View my facilities" link on /lists sets the contributor ID in the contributor select list not the contributor name

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#252]
## Overview

"View my facilities" link on /lists is setting an id in the "Filter by contributor" box on the map page sidebar rather than the name of the contributor

### Expected Behavior

Clicking "View my facilities" navigates to the map page and sets the name of the contributor in the "Filter by contributor" box.

### Actual Behavior

Clicking "View my facilities" navigates to the map page but sets the ID of the contributor in the "Filter by contributor" box. Refreshing the page results in the contributor name being correctly selected.

### Steps to Reproduce

* Log in
* Upload and process a list
* Browse `/lists`
* Click "View my facilities"

### Demo

![2019-03-05 10 57 51](https://user-images.githubusercontent.com/17363/53826492-f18ee080-3f35-11e9-96cc-9396d01ef573.gif)

**Comment by kellyi** [comment]
If I remember correctly it should flip over to "name" once the contributor name/id tuples have returned from the API? The bug here might be that we're displaying the search tab too early, before those results have returned. In other cases we show a loading spinner until the options have come back from the API.

**Comment by rajadain** [comment]
Also, there seems to be crossover between users.

If I log in as a user TT1, and upload a list, and view my facilities I'm taken to `/facilities/?contributors=100`. Then, if I log out, and register / log in as new user TT2, and upload a new list, and view my facilities, I'm taken _again_ to `/facilities/?contributors=100`, instead of `/facilities/?contributors=101`. If I refresh the page somewhere in this sequence, it loads the correct facilities.

**Comment by rajadain** [comment]
It seems like when `UPDATE_ALL_FILTERS` fires _before_ `COMPLETE_FETCH_CONTRIBUTOR_OPTIONS`, it behaves **correctly**, i.e. we see the contributor name, not ID, in the filter field. This is the case in a full page reload.

In a front-end routing case, `UPDATE_ALL_FILTERS` fires _after_.

**Comment by kellyi** [comment]
> Also, there seems to be crossover between users.

Interesting. I wonder if we are using `memo` somewhere accidentally that's not getting cleared?
