### ISSUE TITLE
Add feature to support user deleting an account

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#269]
## Overview

Add option on user profile for users to delete their account

### Is your feature request related to a problem? Please describe.

GDPR compliance requires that users have the option to delete personal information stored in the system

### Describe the solution you'd like

Two options:

1. We add a note to the FAQ that users can be deleted by emailing OAR and requesting the account be deleted. OAR admins then forward the email to the development team.

2. We add a button that lets users delete their account and we are not involved at all

**Comment by jwalgran** [comment]
Our situation is complicated by the fact that we have separated the `User` from the `Contributor` in our data model.

- User
   - email
   - should_receive_newsletter
   - has_agreed_to_terms_of_service
   - is_staff
   - is_active
- Contributor
   - admin (User)
   - name (currently labeled as Account Name)
   - description (currently labeled as Account Description)
   - website
   - contrib_type
   - other_contrib_type

All uploaded data is related to the `Contributor` rather than the `User`. This would make it easier to delete a given `User` account, but there are some questions:

- Do any of the fields on the `Contributor` model fall under "personal" information?
- `Contributor.admin` is currently required. Do we make this nullable? If not, to what `User` do we relate the `Contributor` after the previous `admin` is deleted?

**Comment by dboyer** [comment]
After some reading, my thought is that Name could fall under personal information since there is no requirement that someone enter a brand name rather than their personal name.
