### ISSUE TITLE
Show a summary status for an entire facility list

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#327]
## Overview

We need to clearly tell the contributor if they need to wait for the app to process their CSV, or if the app is waiting on the contributor to confirm or reject matches. 

### Describe the solution you'd like

We can use the area on the left side of the pagination toolbar to show status messages.

<img width="1160" alt="Screen Shot 2019-03-18 at 11 06 50 AM" src="https://user-images.githubusercontent.com/17363/54552911-5e5e9d80-496e-11e9-8a0d-6b163c6daa6c.png">

* If any rows are in a terminal error state, include that in the summary message.
   * "Processing failed on one or more rows"
* If all the rows are in either the `UPLOADED`, `PARSED`, or `GEOCODED` states, show a "wait" message.
* If any rows have matches in the `PENDING` status prompt the contributor to take action.
* If all the rows are in a terminal state, show a "finished processing" message. The terminal states are:
  * Automatic match
  * All proposed matches confirmed or rejected
  * New facility
  * Error

**Comment by rajadain** [comment]
Since the front-end only ever gets one page worth of items, I believe the status for the entire list should be sent from the server. Doing so from the `/lists/8` endpoint seems most reasonable. My approach will be to add it as a computed field on `FacilityListSerializer`, perhaps `status`, with a set of declared states `ERROR`, `PROCESSING`, `PENDING` (or would `AWAITING` be better?), and `COMPLETE`. The front-end will switch the displayed message on these states.

Calculating the status for a list on every API call may be expensive in the long run, and we can consider making this a field on the `FacilityList` model. Would that be a premature optimization?
