### ISSUE TITLE
Allow zooming out to show the entire world / decrease zoom level when panning to feature

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#348]
## Overview

Allow zooming out to show the entire world / decrease zoom level when panning to feature.

### Is your feature request related to a problem? Please describe.

In less dense areas the map appears broken

![Line 9 in spreadsheet](https://user-images.githubusercontent.com/17363/54713465-e928cf00-4b0b-11e9-981d-8d94e83d0a33.png)

### Describe the solution you'd like

* Change the map setup / min zoom so that the entire world is visible by default
* Decrease zoom level when panning to a facility.
 
### Additional Context

https://stackoverflow.com/questions/9893680/google-maps-api-v3-show-the-whole-world

**Comment by rajadain** [comment]
The underlying google-map-react library we're using explicitly does not support zoom levels lower than 4, because the author hasn't figured out a way to show the same marker (single instance in React) multiple times on the map for when it wraps around at lower zoom levels: https://github.com/google-map-react/google-map-react/issues/544.

Can this feature be deferred until later? Can we change the initial location to be something better instead?

**Comment by jwalgran** [comment]
We can defer this. It was explicitly discussed on a check-in call and it is not critical to show the entire world.

**Comment by jfrankl** [comment]
I wanted to chime in with a different perspective. My impression is that showing the entire world is critical because when a user performs a search, they want to see all of the results. When I used to the application for the first time, I only saw a few results on the map. At first I assumed that there were not other markers on the map, because the expected behavior is to see all of the results when you search. However, when I panned the map, I saw additional markers that were outside of my initial map view.

**Comment by kellyi** [comment]
As part or as prep for this card, we may want to plan to replace the react-google-map library we are currently with just using Google Maps directly within the FacilitiesMap component.

That component already has quite a bit of imperative code set up around manipulating map behaviors, so the path of removing the library may not be too burdensome -- and the library itself seems to be the main constraint on changing the zoom level.
