### ISSUE TITLE
Adjust behavior of My Facilities link for contributors with no active lists

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#431]
## Overview

#340 removes contributors with 0 active public lists from the contributors endpoint & in turn doesn't display them in the client's list of contributor options.

However, this causes an error with the "My Facilities" link in the navigation dropdown, since for contributors with no lists the link remains but the search gets into a mildly wonky state described https://github.com/open-apparel-registry/open-apparel-registry/issues/413#issuecomment-477704102 when the contributors list doesn't have a match for the ID.

For this card, determine and implement the proper behavior for the "My Facilities" Link.

### Describe the solution you'd like

https://github.com/open-apparel-registry/open-apparel-registry/issues/413#issuecomment-477704102 has some suggestions

### Additional Context

There's another "My Facilities" link on the lists page. However, this link only shows up when there are lists.

**Comment by jwalgran** [comment]
We changed the "My Facilities" page to show claimed, rather than contributed facilities, with an informative message if no facilities have been claimed.

<img width="423" alt="Screen Shot 2019-10-28 at 9 09 39 AM" src="https://user-images.githubusercontent.com/17363/67695733-cfcde800-f962-11e9-9bec-4c4ec89d8c76.png">
