### ISSUE TITLE
Configure CORs

### ISSUE THREAD

**Issue by rbreslow** [open-apparel-registry/open-apparel-registry#46]
CORS isn't configured to allow the frontend to access the API in development:

<img width="1078" alt="screen shot 2019-01-03 at 10 34 34 am" src="https://user-images.githubusercontent.com/14170650/50646427-ffc77d00-0f43-11e9-9c65-b8d801c227cb.png">

* Evaluate the best approach to resolve issues with CORS and execute

See related issue: https://github.com/raster-foundry/prediction-api/pull/85

See discussion: https://github.com/azavea/open-apparel-registry/pull/42#discussion_r245040083

**Comment by kellyi** [comment]
Heads up that I am going to try to fix this in passing while working on #70 because signup and login require making a post request.

I think the preferred solution here is to use some version of Create React App's proxy -- https://facebook.github.io/create-react-app/docs/proxying-api-requests-in-development -- which matches how we set up Webpack Dev Server in other projects.

Since the production app will be served from same origin using Django-SPA, it seems like we may not need the CORS middleware in Django.
