### ISSUE TITLE
Support uploading Excel xls and xlsx files

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#484]
## Overview

Users can upload lists in xlsx and xls formats. 

### Is your feature request related to a problem? Please describe.

There are consistently reported issues with users who do not upload lists in CSV format or have trouble saving in that format. Accepting more file formats would cut down on the troubleshooting needed to support facility list uploads. 

### Describe the solution you'd like

Users can upload lists in xls or xlsx format in addition to CSV.

https://pypi.org/project/openpyxl/ and https://pypi.org/project/xlrd/ look like popular library choices.

**Comment by jwalgran** [comment]
The scope of this issue changes significantly depending on what file formats we support. Reading sheets out of an Excel workbook in xls or xlsx format is relatively straightforward. Incorporating support for PDFs is a much larger task, approaching an order of magnitude increase in complexity.

Can this be narrowed to Excel support?

**Comment by jwalgran** [comment]
CC @nataliegrillon and @katieashaw 

The current title of this issue is "Support uploading non-CSV files." Can we be more specific and re-title it "Support uploading Excel .xls and .xlsx files?" Do we need to support other file types?

**Comment by katieashaw** [comment]
That makes sense to me. It might not be necessary, but do you think we should consider supporting Numbers files as well?

**Comment by nataliegrillon** [comment]
I think excel should be fine- we haven't seen anyone use any other programs.

Best,

Natalie
----
Natalie Grillon
Project Director, Open Apparel Registry
+ 1 413 884 3355 // *natalie@openapparel.org <natalie@openapparel.org> *
*Open Apparel Registry <http://openapparel.org>*
Search the map here <http://openapparel.org>
Watch a 90 second explainer about the Open Apparel Registry here
<https://youtu.be/hrqQc3CVdHQ>
Learn more about the tool here <https://info.openapparel.org/>

**Comment by jwalgran** [comment]
Thanks for the feedback. I did some searching to see if there is an easy way to get data out of a Numbers file but I did not find anything promising.

**Comment by rajadain** [comment]
This is the current sequence of creating a new list in OAR.
The **bold** lines are those affected by the file format:

* File Validation
    - Ensure file is specified
    - Ensure file is loaded into memory
    - Ensure file does not exceed max size
* Header
    - **Extract header from file**
    - **Validate header**
* Contributor
    - Extract user as contributor from request
* Name
    - Get list name from request data
    - If not in request data, use filename
* Description
    - Get description from request data, else None
* Replaces, if specified
    - Ensure it is an integer
    - Ensure it is a valid facility list ID
    - Ensure the facility list it is replacing hasn't already been replaced
* New List
    - Make new facility list using contributor, name, description, file_name, header, and replaces
    - Save it
* Replaced List
    - If replacing a list, mark it as inactive
    - Save it
* Items
    - Initialize to empty list
    - **For each line in the file (except for the header):**
        - Add a new facility list item to items array, with a row_index, facility_list (set to New List from above), and **raw_data which is the decoded line from the file**
    - Bulk create all items in list
    - If on Staging or Production, submit jobs for the new list
* Return serialized new list

Given the above, I will make helper methods in the `FacilityListViewSet` class for each of the bold lines, and will replace the direct implementation with the helper methods.

**Comment by rajadain** [comment]
OpenPyXL has a number of performance costs:

> Memory use is fairly high in comparison with other libraries and applications and is approximately 50 times the original file size, e.g. 2.5 GB for a 50 MB Excel file. 
> -- <cite>[OpenPyXL Docs/Performance](https://openpyxl.readthedocs.io/en/stable/performance.html#performance)</cite>

They mention an [optimized read-only mode](https://openpyxl.readthedocs.io/en/stable/optimized.html#read-only-mode), which can read unlimited amounts of data with (near) constant memory consumption. In their [benchmarks](https://openpyxl.readthedocs.io/en/stable/performance.html#read-performance) against xlrd (which _does_ have limited support for `.xlsx` files), the optimized read-only mode gets very close to (but never beats) the xlrd times.

OpenPyXL is more feature-rich. For example, when it opens a file it converts dates and times to Python datetimes. xlrd does not.

> One major difference between the libraries is that openpyxl’s read-only mode opens a workbook almost immediately making it suitable for multiple processes, this also reduces memory use significantly. xlrd does also not automatically convert dates and times into Python datetimes, though it does annotate cells accordingly but to do this in client code significantly reduces performance.
> -- <cite>[OpenPyXL Docs/Performance](https://openpyxl.readthedocs.io/en/stable/performance.html#read-performance)</cite>

But since we're only reading plain text values, these features don't matter.

Given the above, there are three possible approaches:

1. Use xlrd to open `.xls` files and OpenPyXL to open `.xlsx` files
    - Pros:
        + Full featured support of every format
    - Cons:
        - Separate parsing code
        - Potential performance issues with OpenPyXL, especially with large files
2. Use xlrd to convert `.xls` files to `.xlsx` and then open them with OpenPyXL, and open `.xlsx` files directly with OpenPyXL
    - Pros:
        + Full featured support for every format
        + Unified parsing (since everything will be `.xlsx`)
    - Cons:
        - Overhead of file conversion, especially with large files
        - Potential performance issues with OpenPyXL, especially with large files
3. Use xlrd to read both `.xls` and `.xlsx` files
    - Pros:
        + High read performance, low memory use
        + Unified parsing (since everything will be xlrd)
    - Cons:
        - May not read all `.xlsx` files
            - This fact is stated by the [OpenPyXL documentation](https://openpyxl.readthedocs.io/en/stable/performance.html#read-performance):
                > Performance is measured using a file provided with a previous bug report and compared with the older xlrd library. xlrd is primarily for the older BIFF file format of .XLS files but it does have limited support for XLSX.

                But I have not found independent corroboration of it. The xlrd project [claims to support](https://pypi.org/project/xlrd/#description) all `.xlsx` files:
                > Extract data from Excel spreadsheets (.xls and .xlsx, versions 2.0 onwards) on any platform.

Both libraries [recommend](https://openpyxl.readthedocs.io/en/stable/index.html?highlight=defusedxml#security) [using](https://xlrd.readthedocs.io/en/latest/vulnerabilities.html) [defusedxml](https://pypi.org/project/defusedxml/) to protect against XML vulnerabilties in `.xlsx` files.

OpenPyXL is more actively developed, but as long as xlrd does the one thing we need well, I think it's an acceptable choice. The most recent version of OpenPyXL was March 2019, and for xlrd is December 2018.

Given the above, I think the best way is to start with option 3, and then turn to 1 if we can find `.xlsx` files that aren't being handled correctly.

**Comment by jwalgran** [comment]
Thank you for the in-depth analysis. I agree with this:

>I think the best way is to start with [us[ing] xlrd to read both `.xls` and `.xlsx` files], and then turn to [us[ing] xlrd to open .xls files and OpenPyXL to open .xlsx files] if we can find .xlsx files that aren't being handled correctly. 

We are requiring our contributors to submit simple, single sheet workbooks so we have a good shot at getting all the support we need from `xlrd`.

**Comment by rajadain** [comment]
Hmm, it should be noted that xlrd is no longer under active development: https://groups.google.com/forum/#!msg/python-excel/P6TjJgFVjMI/g8d0eWxTBQAJ

And the maintainer suggests using OpenPyXL if one is only using `.xlsx` files:

> The packages in question are xlrd, xlwt and xlutils. I will be upfront and say you should no longer be using these unless you have a particular need to work with .xls files. If you only work with .xlsx files, and that's the only Excel format you should look to create nowadays, then you should be using openpyxl instead.

But since we _do_ need to support `.xls` files, I'm going to keep going with the decision above.
