### ISSUE TITLE
Determine solution to interactively engage with application from China

### ISSUE THREAD

**Issue by hectcastro** [open-apparel-registry/open-apparel-registry#513]
There is some Google Maps based functionality within the application that needs to be configured (and has the potential to behave) in slightly different ways when interacted with from inside and outside of China.

We need a mechanism to view the application locally (office network), but have the application interactions be initiated from networks within China. For example:

- VPN
- Virtual desktop/machine provider
- SOCKS proxy
- ...

Any of these options can work, but we need to determine the best one that supports interactive UI testing.

Related to https://github.com/open-apparel-registry/open-apparel-registry/issues/506

**Comment by rbreslow** [comment]
I did some research into VPN providers that have servers located in mainland China and settled on trying out [PureVPN](https://purevpn.com). I signed up for their 1 month package which was $10.95. The credentials for our billing account are under `Shared-Azavea Ops/PureVPN`.

The setup was strange, because although they have servers in China, they don't offer the OpenVPN configuration files (in general, their support site is lacking with broken instructions, etc). I tried making my own configuration, but after my client would authenticate, the connection would just stall out. I spoke with someone over live chat and they explained that I need to use their proprietary client if I want to use the OpenVPN protocol for their Chinese servers on macOS (which doesn't seem right), but that I could connect via `L2TP over IPSec` or `IKEv2` without their client.

I went into `System Preferences` -> `Network` and added a new interface:

<img width="459" alt="image" src="https://user-images.githubusercontent.com/1774125/57953800-1fda5600-78bf-11e9-8906-f06531eea73a.png">

Which is configured like this:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/1774125/57953816-2ec10880-78bf-11e9-8ef3-3fb1d8cc86a4.png">

Under `Authentication Settings` you need to enter the [shared secret](https://support.purevpn.com/what-is-the-pre-shared-secret-key-for-l2tp):

<img width="413" alt="image" src="https://user-images.githubusercontent.com/1774125/57953836-3aacca80-78bf-11e9-8eba-fa77733e9268.png">

Make sure `Send all traffic over VPN connection` is checked under `Advanced`:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/1774125/57953903-67f97880-78bf-11e9-90d6-946415d09106.png">

From their list of VPN servers (which is different in the [client portal](https://my.purevpn.com/serverlocations) vs their [support article](https://support.purevpn.com/vpn-servers)), we can choose from:

- `cn1.pointtoserver.com` - Beijing, China
- `vlus-cn1.pointtoserver.com` - Guangdong, China
- `cn-hn1.pointtoserver.com` - Shanghai, China

The credentials for the VPN user are under `Shared-Civic Apps/PureVPN (VPN User)`.

**Comment by jwalgran** [comment]
I was able to set this up on my machine, successfully connect to `cn-hn1.pointtoserver.com`, browse openapparel.org and recreate the resource loading failures. Thanks.
