### ISSUE TITLE
Superusers can view all lists

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#547]
## Overview

Allow superusers to view all lists but not modify them.

### Is your feature request related to a problem? Please describe.

It is difficult to answer support questions that contributors have about their uploaded lists without being able to see them.

### Describe the solution you'd like

- Allow superusers to browse any list detail page.
- Add a superuser dashboard page.
  - After choosing a contributor from a single-select dropdown links to all of the contributors lists are displayed. Show upload date for each and order by upload date descending.

**Comment by kellyi** [comment]
https://github.com/open-apparel-registry/open-apparel-registry/issues/546 was merged so this is no longer blocked. However, we should coordinate routing because https://github.com/open-apparel-registry/open-apparel-registry/issues/517 will also involve working with this dashboard route.

I was thinking that `/dashboard` could be a page that had links to two subpages:

- `/dashboard/claims` for working with facility claims
- `/dashboard/lists` for working with facility lists

These routes will have to be set up in a switch in the current Dashboard component, which catches `/dashboard` at the top level. We'll also need some kind of minimal interface in the Dashboard component which has two react-router-dom `Link`s to `/dashboard/claims` and `/dashboard/lists`

**Comment by kellyi** [comment]
https://github.com/open-apparel-registry/open-apparel-registry/pull/557 adds the routing described above for the dashboard page
