### ISSUE TITLE
Remove Filestack and user profile photo related frontend code

### ISSUE THREAD

**Issue by rbreslow** [open-apparel-registry/open-apparel-registry#6]
- remove Filestack
- remove profile-photo related code from frontend, as we'll implement it anew if it's determined that we should add this functionality to the application

**Comment by kellyi** [comment]
Filestack was used only for user profile photos. While working on this one we should determine whether we need to retain profile photo functionality and, if so, determine how we're going to implement it.

**Comment by dboyer** [comment]
We do not need user profiles for the immediate relaunch of the site. 

Profile photos were originally included so that a brand could upload a logo that would then appear next to their name in the contributor list for a facility. That functionality was not implemented in the legacy site, but we may want to include it in the future.

**Comment by kellyi** [comment]
I updated the issue title and initial comment to indicate that we should also remove any residual profile-photo-related code from the frontend.
