### ISSUE TITLE
DRAFT: Make disambiguation popup work with vector tile layer

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#740]
# Draft

This is a draft issue, and it will need to clarify specs and formalize what
counts as "done" before work begins on it.

Check with the issue's creator before starting work on this issue.

## Overview

A clear description of the feature request.

### Describe the solution you'd like

- Include name and address in the vector tile for map features.

### Additional Context

Optional. Add any other context, screenshots, gifs, etc about the feature request here.

**Comment by kellyi** [comment]
We discussed this being very similar to the work for #741. It appears that we can use `ST_ClusterWithin` to do this via PostGIS in the tiler file, and then give clustered features an array property that would include dicts for each facility that has been clustered in that feature with the OAR ID, name, and address of the facility.

From there we can set up the react/leaflet component to conditionally render these kinds of markers in some way to indicate that they are clusters, attaching the disambiguation popup to have it work as before.

We also considered not limiting the disambiguation feature by zoom level -- if it's zoomed in closely enough to render a marker rather than the grid, clicking on a cluster could show the popup without zooming in. We could make clicking on an item in the popup also pan the map, if necessary, if we're not at the max zoom level.
